sample_packing: true
flash_attention: false
sdp_attention: true
load_in_8bit: false
special_tokens:
  pad_token: "<|pad|>"
adapter: lora
lora_r: 64
lora_alpha: 128
lora_target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]
lora_dropout: 0
lora_qkv_kernel: false
lora_o_kernel: false
lora_mlp_kernel: false
micro_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: true
learning_rate: 1e-4
lr_scheduler: cosine
warmup_ratio: .05
weight_decay: 0.01
max_grad_norm: 1.0
optimizer: adamw_torch_fused
save_total_limit: 1
save_only_model: true
logging_steps: 10
output_dir: ./output
bf16: true
tf32: true
chat_template: tokenizer_default
seed: 42
